### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by andreiconstantinescu** [meggrasse/Upgrade#3]
I am new to swift dev. How does the `Config.h` should look like? 
It is required in the header `Bridgind-Header.h`

Thanks :)

Andrei.

**Comment by meggrasse** [comment]
Hi Andrei! `Config.h` includes the keys I use to access the Spotify API [`kClientID`, `kCallbackURL`, and `kSessionUserDefaultsKey` in my code]. Spotify includes a tutorial as to how you can obtain your keys [here](https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/)
